version: '3'
services:

  # Frontend service
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

  # Backend service
  backend:
    build: ./backend
    ports:
      - '4000:4000'
    depends_on:
      - mongo_db

  # MongoDB service
  mongo_db:
    image: mongo
    restart: always
    ports:
      - '27017:27017'

  # Seed the MongoDB with sample insurance data
  mongo_seed:
    image: mongo
    links:
      - mongo_db
    volumes:
      - ./seed-db:/seed-db
    command: /seed-db/import.sh
